[package]
name = "syn-grammar"
version = "0.1.0"
edition = "2024"

[dependencies]
syn = { version = "2.0", features = ["full", "parsing", "printing", "extra-traits"] }
quote = "1.0"
proc-macro2 = "1.0"
derive-syn-parse = "0.2.0"
proc-macro-error = "1.0"
syn-grammar-macros = { path = "./macros" }

[features]
default = []
jit = ["dep:tempfile"]
