[package]
name = "syn-grammar"
version = "0.1.0"
edition = "2024"

[dependencies]
syn = { version = "2.0", features = ["full", "parsing", "printing", "extra-traits"] }
quote = "1.0"
proc-macro2 = "1.0"
derive-syn-parse = "0.2.0"
proc-macro-error = "1.0"

[dependencies.tempfile]
version = "3.10"
optional = true

[features]
default = []
jit = ["dep:tempfile"]

[dev-dependencies]
insta = "1.34"
syn-grammar = { path = ".", features = ["jit"] } 
